### ISSUE TITLE
默认关闭双拼下支持全拼问题

### ISSUE THREAD

**Issue by lovelock** [zhuangzhemin/Rime#4]
默认开启双拼（形）下支持全拼，这会造成一些混淆，比如keng 本来在双拼下是没有异议就是可能，但如果同时支持全拼，首选字会是坑，作为纯粹的双拼用户，不需要默认打开这个功能，但我没有找到在那里改，可以简单说一下在哪里改，我自己来改也行。多谢

**Comment by lovelock** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/2208731/233024280-4249eae4-3378-40a9-b28d-b08de7ac3fb8.png">

这样改了之后好像是有用，但不确定会不会导致其他不带码表的词库无法使用
<img width="723" alt="image" src="https://user-images.githubusercontent.com/2208731/233024452-0c9373ed-95b4-43ef-a9ee-07e15305bb0d.png">

**Comment by zhuangzhemin** [comment]
> <img alt="image" width="1416" src="https://user-images.githubusercontent.com/2208731/233024280-4249eae4-3378-40a9-b28d-b08de7ac3fb8.png">
> 
> 这样改了之后好像是有用，但不确定会不会导致其他不带码表的词库无法使用 <img alt="image" width="723" src="https://user-images.githubusercontent.com/2208731/233024452-0c9373ed-95b4-43ef-a9ee-07e15305bb0d.png">

就是这样改的。
